[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"
license = "MIT"

[[example]]
name = "get_channel_info"
path = "get_channel_info.rs"

[dependencies]
chzzk = { path = "../chzzk" }
tokio = { version = "1.42.0" }
